name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: if you need to run your Python scripts during build
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt  # if you have one
      # - name: Run build scripts
      #   run: python src/scripts/py/main.py

      # Create a directory for deployment and copy necessary files
      - name: Prepare deployment
        run: |
          mkdir deploy
          cp -r src/scripts/index.html src/scripts/js src/scripts/styles deploy/
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy # The folder we're deploying
          branch: gh-pages # The branch to deploy to
